### PR TITLE
docs: add more struct tag type examples

### PR DESCRIPTION
**Pull request by pershin-daniil**

### CODE REVIEW

**Comment by pershin-daniil** [comment]
https://github.com/golangci/golangci-lint/pull/4519

**Comment by ldez** [comment]
hello,

tagliatelle as a CLI command doesn't have the same default as the lib inside golangci-lint.

**Comment by ldez** [comment]
The goal is not to be exhaustive because you can define all the tag names you want.

This is just an example.

**Comment by ldez** [comment]
The readme doesn't have to be synced with golangci-lint doc, it's just an example.

**Review by ldez — APPROVED** [review]

**Pull request merged**
